version: "3"

tasks:
  swap:
    cmds:
      - go run ./swap/main.go

  reverse:
    cmds:
      - go run ./reverse/main.go

  factorial:
    cmds:
      - go run ./factorial/main.go

  fib:
    cmds:
      - go run ./fib/main.go

  pall:
    cmds:
      - go run ./pallindrum/main.go

  slice:
    cmds:
      - go run ./slice/main.go

  min-sort:
    cmds:
      - go run ./sort/sort_with_min/main.go

  max-sort:
    cmds:
      - go run ./sort/sort_with_max/main.go

  bubble:
    cmds:
      - go run ./sort/bubble_sort/main.go

  todo:
    cmds:
      - go run ./todolist/main.go
